### ISSUE TITLE
Build on stable rust

### ISSUE THREAD

**Issue by FredrikNoren** [jquesada2016/firebase-wasm-rs#2]
Hi,

Another question; would it be possible to get this to build on stable rust?

**Comment by jquesada2016** [comment]
@FredrikNoren yes it would. Nightly is currently only required because of the use of some convenient methods that are only available on nightly.

**Comment by jquesada2016** [comment]
Fixed in #5d6555a

**Comment by FredrikNoren** [comment]
@jquesada2016 Awesome!
